import type { MetadataRoute } from 'next'
import factPaths from './fact-urls.json'

const BASE = 'https://smartassfacts.com'

// Reads the committed fact-url list (generated by scripts/gen-fact-urls.mjs) so
// the build is fast and reliable. Re-run that script when fact content changes.
export default function sitemap(): MetadataRoute.Sitemap {
  const staticRoutes = [
    '',
    '/facts',
    '/myths',
    '/vs',
    '/random',
    '/about',
    '/how-it-works',
    '/educators',
    '/leaderboard',
    '/privacy',
    '/terms',
    '/cookies',
  ]

  const facts = factPaths as string[]

  // Category pages = the distinct category slugs that actually have facts
  // (derived from the fact list, so empty alias slugs are excluded).
  const categorySlugs = [...new Set(facts.map(p => p.split('/')[0]))]

  const staticEntries: MetadataRoute.Sitemap = staticRoutes.map(path => ({
    url: `${BASE}${path}`,
    changeFrequency: 'weekly' as const,
    priority: path === '' ? 1 : 0.7,
  }))

  const categoryEntries: MetadataRoute.Sitemap = categorySlugs.map(slug => ({
    url: `${BASE}/facts/${slug}`,
    changeFrequency: 'weekly' as const,
    priority: 0.7,
  }))

  const factEntries: MetadataRoute.Sitemap = facts.map(p => ({
    url: `${BASE}/facts/${p}`,
    changeFrequency: 'monthly' as const,
    priority: 0.5,
  }))

  return [...staticEntries, ...categoryEntries, ...factEntries]
}
